# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
image:
    file: .gitpod.Dockerfile
tasks:
  - init: yarn install --immutable
    command: yarn start && make run


